### ISSUE TITLE
Mention that the current release does no longer support Sierra

### ISSUE THREAD

**Issue by EugenMayer** [tluck/Lenovo-T460-Clover#1]
At least the AppleACL.kext of v2017.09.19 will no longer work under Sierra .. looking at the change logs i have seen that you patched it for High Sierra.

You might still want to mention it, that it will not work under Sierra ( which is the current stable release ).

i picked the AppleACL from v2017.05.28 and it worked again

**Comment by tluck** [comment]
Sorry I recompiled Lilu today with 10.12 SDK so the bundle should work on both Sierra and High Sierra

**Comment by EugenMayer** [comment]
@tluck are you aware that Lilu was working, but AppleACL was not?

**Comment by tluck** [comment]
Yes. well both kexts should work now on Sierra or High Sierra. i tested on 3 other boxes. i just dont have my T460 anymore.

**Comment by EugenMayer** [comment]
Thank you!

**Comment by EugenMayer** [comment]
@tluck AppleACL still disfunctional under Sierra - i had to migrate back to the Mai version

**Comment by tluck** [comment]
did you replace both Lilu and AppleALC ?

**Comment by EugenMayer** [comment]
Yes
On 27 Sep 2017 10:59 AM, tluck <notifications@github.com> wrote:did you replace both Lilu and AppleALC ?
