### ISSUE TITLE
what about t570?

### ISSUE THREAD

**Issue by wenco** [tluck/Lenovo-T460-Clover#11]
i5-7200u
hd620 & g940mx  1920x1080

**Comment by rsdev69** [comment]
everything works except 940mx. NVIDIA Optimus do not support macOs.

**Comment by wenco** [comment]
> 
> 
> everything works except 940mx. NVIDIA Optimus do not support macOs.

use your t460 clover?my t570 have a fingerprint and sd card raw,how can i found kexts?thx

**Comment by rsdev69** [comment]
my model Е560 and i use DSDT.T560. All work fine.
in your clover use DSDT.T470. 
fingerprint will not work, sd card work.

**Comment by tluck** [comment]
cool!

**Comment by wenco** [comment]
thanks,i try it next time.
