### ISSUE TITLE
Catalina reboot

### ISSUE THREAD

**Issue by wudimenghuan** [tluck/Lenovo-T460-Clover#24]
Startup, 3-5 minutes later,reboot

**Comment by wudimenghuan** [comment]
when i upgrade whatevergreen and ps2
it fixed

**Comment by tluck** [comment]
great. i updated the repo with the most recent acidanthera lilu family of kexts (AppleALC, Whatevergreen), and added VoodooPS2 2.x

**Comment by wudimenghuan** [comment]
i used your 11.25 version and it start to reboot again

**Comment by wudimenghuan** [comment]
@tluck how to check system log?
