### ISSUE TITLE
Internet not working

### ISSUE THREAD

**Issue by TudorGruian** [tluck/Lenovo-T460-Clover#25]
Internet(ethernet) seems to not be working on the latest version. At least for me, where I am using a network installer method to install the OS.

The issue might be from IntelMausiEthernet ? Idk..

**Comment by tluck** [comment]
huh. i posted the version the developer created? does the kext load?

**Comment by grandtiger** [comment]
@tluck I just updated to the latest release last night, both USB Wi-Fi dongle and Ethernet LAN are still working. I am not 100% sure that everything is working given my limited experience with this, but it seems fine to me so far, nothing abnormal that I have observed.

But I had a different issue during the upgrade. When I ran ```./_kext-install.command```, my T460 just crashed half way through the installation. I did it again after it rebooted, and that completed successfully. What is the right way to apply update? Do I need to boot using the USB installer instead? Thanks a lot for your work!

**Comment by tluck** [comment]
a crash? odd. well do know what caused the crash?

**Comment by grandtiger** [comment]
@tluck unfortunately I don’t know what caused the crash. Where to look for such information? It hasn’t crashed tonight, I have been using it for a few hours. I did notice that the bluetooth stopped working, it was able to detect a device last night before the upgrade.

**Comment by anhtutran37** [comment]
No problem with intelmausi kext. But I have issue with capslock's light, 2.0.3 works perfect with me

**Comment by TudorGruian** [comment]
Apparently, Mausi seems to not load, at least for me. The only release that Mausi worked is the August Clover. Right now, the network installer for Catalina just works.

**Comment by wudimenghuan** [comment]
I think this cause the reboot

**Comment by wudimenghuan** [comment]
When I’m downloading a file, Catalina usually reboot

**Comment by TudorGruian** [comment]
(Offtopic) Also occuring random crashes with the latest release

After the installer succeeded with the August Release, I installed the latest release and Ethernet Seems to work after the installed. But now, I have random crashes. It may be related to ethernet as @wudimenghuan pointed out

**Comment by TudorGruian** [comment]
I can confirm that IntelMausiEthernet is problematic in the latest release. By disabling the kext, my laptop wouldn't randomly kernel panic anymore.

**Comment by TudorGruian** [comment]
Abc

**Comment by tluck** [comment]
on IntelMausEthernet> i wonder if turning TSO off will make a difference?
edit IntelMausiEthernet.kext/Contents/Info.plist
change to:

				<key>enableTSO4</key>
				<false/>
				<key>enableTSO6</key>
				<false/>

**Comment by tluck** [comment]
or get the original here:
https://www.insanelymac.com/forum/files/file/396-intelmausiethernet/

**Comment by TudorGruian** [comment]
Still the same, the problem is with the kext itself.
