### ISSUE TITLE
Advanced gestures working?

### ISSUE THREAD

**Issue by EugenMayer** [tluck/Lenovo-T460-Clover#3]
Are any gestures working, like three finger down swipe or even a normal tap, two finger from right for notifications and so on.

Especially scrolling feels pretty bad, stucks often or simply does not register the two finger scroll.

Any way to improve that?

**Comment by tluck** [comment]
Gestures that are supported by VoodooPS2 are working. but since it is not an AppleMagic Pad not all gestures will work. i dont have my T460 anymore, it seemed to always scroll very nicely?

**Comment by EugenMayer** [comment]
Did you upgrade to a 560? And no, actually the touchpad is one of the biggest issues with tosh on this device i would say. Anything else is really smooth
