### ISSUE TITLE
[OpenCore] Kernel hangs on boot (T460)

### ISSUE THREAD

**Issue by mateodif** [tluck/Lenovo-T460-Clover#31]
I can't get it to boot using OpenCore 0.5.8 and a recovery image of 10.15.4 (also tried 10.15.3) that I got with gibMacOS script. I tried a lot of combinations (like using different usb drives, modifying config.plist, etc) but none of them worked.
I have the i5 6300U thinkpad, 1080p, 16GB of RAM and a SIM slot, if any of that matters.

Any idea of what could be wrong?

Here's a log, I don't think it'll be of any use though, as it doesn't hang on OpenCore.
[opencore-2020-05-05-154040.txt](https://github.com/tluck/Lenovo-T460-Clover/files/4581948/opencore-2020-05-05-154040.txt)
It hangs on the kernel bootup phase, I haven't found a nice way of getting logs out of the kernel so I uploaded a video you can see here: https://streamable.com/ez6gqm

Cheers.

**Comment by junaedahmed** [comment]
Hi @mateodif ,
My advice would be to try to install with tluck's clover build first see if that works

**Comment by mateodif** [comment]
Nevermind, tried yet another USB drive and... it worked. Amazing. Thanks!
