### ISSUE TITLE
T460 reliably unable to reboot after running _kext-install.command

### ISSUE THREAD

**Issue by fosspill** [tluck/Lenovo-T460-Clover#33]
Hi!

I've been unable to sign up for insanelymac so I'm posting here in hope of some help.

While following the  insanelymac guide perfectly my T460 reliably stops booting (kernel panic) after running _kext-install. If I skip this step my machine keeps booting.

After a panic I'm unable to boot into the install even with safemode, so it feels like the install is broken. (Regardless of Clover config used)

What would be the right thing to do to troubleshoot this? Do the kext install manually, presumably? Or would trying opencore be smarter?

**Comment by tluck** [comment]
_kext-install was the old way of installing to /Library/Extensions. in general you dont that step. You can remove any custom kexts from /Library/Extension and just let clover or OC inject them from the ESP/EFI location.
