### ISSUE TITLE
Catalina 10.15.5 would not connect to HDMI display automatically using this EFI

### ISSUE THREAD

**Issue by richardkindom** [tluck/Lenovo-T460-Clover#38]
please fix it. Thanks

**Comment by rsdev69** [comment]
> please fix it. Thanks

Add igfxonln=1 to boot-args and HDMI port fixed.

**Comment by richardkindom** [comment]
> > please fix it. Thanks
> 
> Add igfxonln=1 to boot-args and HDMI port fixed.

Hi Buddy,
thanks for your reply.
Unfortunately, it did not work with my T460. Any other idea?

**Comment by richardkindom** [comment]
hello all, after I upgrade my lilu and whatevergreen to newest version, it works!

thanks.
