### ISSUE TITLE
Power off became reboot after sleep

### ISSUE THREAD

**Issue by richardkindom** [tluck/Lenovo-T460-Clover#40]
Hey everyone, I found out that when I made T460 sleep after a while, woke up it, and then shut it down, it rebooted directly instead.
When shutting down at the very end stage, a noise was generated from speaker.

Could anyone help me?
Editor Note: correct speaker

**Comment by tluck** [comment]
do you have this in place? SSDT-HACK-T460.dsl - this seemed to make a difference on reboot after shutdown...

**Comment by richardkindom** [comment]
It's placed properly in EFI. For most of cases, my computer shut down perfectly unless it slept for a while and woke up. Weird stuff.

**Comment by richardkindom** [comment]
Hi I have switched to open core EFI and everything goes well. so closed
